name: .NET CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-test:
  
    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests with coverage
      run: |
        dotnet test \
            --configuration Release \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile="**/*.generated.cs"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator \
            -reports:coverage/**/coverage.cobertura.xml \
            -targetdir:coverage/report \
            -reporttypes:"HtmlSummary"

    - name: Code coverage summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        format: markdown
        output: both

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/report

    - name: Commit coverage badge
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add coverage-summary.svg
        git commit -m "Update coverage badge" || echo "No changes"
        git push